export const ShopActionTypes = {
    GETTING_COLLECTIONS_START: 'GETTING_COLLECTIONS_START',
    GETTING_COLLECTIONS_SUCCESS: 'GETTING_COLLECTIONS_SUCCESS',
    GETTING_COLLECTIONS_FAILURE: 'GETTING_COLLECTIONS_FAILURE',
}